import { useState, useContext } from "react";
import axios from "axios";
import { motion } from "framer-motion";
import { Droplet, HeartHandshake, Download } from "lucide-react";
import jsPDF from "jspdf";
import { AuthContext } from "../context/AuthContext";

export default function BloodDonation() {

  const { user } = useContext(AuthContext)

  const [bloodGroup, setBloodGroup] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const checkCompatibility = async () => {
    try {

      setLoading(true)

      const token = localStorage.getItem("token")

      const res = await axios.post(
        "http://127.0.0.1:8000/api/blood-donation/check",
        {
          blood_group: bloodGroup
        },
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      )

      setResult(res.data)

    } catch (error) {

      alert("Error checking blood compatibility")

    } finally {
      setLoading(false)
    }
  }

  // 🔥 ADVANCED PDF FUNCTION
  const downloadPDF = () => {

    if (!result) return

    const doc = new jsPDF()

    // LOGO
    const logo = new Image()
    logo.src = "/logo.png"

    logo.onload = () => {

      doc.addImage(logo, "PNG", 15, 10, 30, 30)

      // TITLE
      doc.setFontSize(20)
      doc.setTextColor(40, 40, 40)
      doc.text("AI Healthcare Report", 55, 20)

      doc.setFontSize(14)
      doc.setTextColor(100)
      doc.text("Blood Donation Compatibility", 55, 30)

      // LINE
      doc.setDrawColor(200)
      doc.line(15, 45, 195, 45)

      // USER INFO
      doc.setFontSize(12)
      doc.setTextColor(50)

      doc.text(`Name: ${user?.name || "User"}`, 15, 60)
      doc.text(`Email: ${user?.email || "-"}`, 15, 70)

      const today = new Date().toLocaleString()
      doc.text(`Date: ${today}`, 15, 80)

      // BLOOD GROUP
      doc.setFontSize(14)
      doc.setTextColor(0)
      doc.text(`Blood Group: ${result.data.blood_group}`, 15, 100)

      // DONATE
      doc.setFontSize(12)
      doc.setTextColor(0)

      doc.text("Can Donate To:", 15, 120)
      doc.text(result.data.can_donate_to.join(", "), 15, 130)

      // RECEIVE
      doc.text("Can Receive From:", 15, 150)
      doc.text(result.data.can_receive_from.join(", "), 15, 160)

      // FOOTER
      doc.setFontSize(10)
      doc.setTextColor(150)
      doc.text(
        "Generated by AI Healthcare System",
        15,
        280
      )

      doc.save("AI_Blood_Report.pdf")
    }
  }

  return (

    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-red-700 via-pink-600 to-rose-600">

      <motion.div
        initial={{ scale: 0.8, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        className="bg-white/10 backdrop-blur-xl border border-white/20 p-10 rounded-3xl shadow-2xl w-[520px]"
      >

        <div className="text-center mb-6">

          <div className="flex justify-center mb-3">
            <Droplet size={45} className="text-red-300 animate-bounce"/>
          </div>

          <h2 className="text-3xl font-bold text-white">
            Blood Donation Compatibility
          </h2>

        </div>

        <select
          value={bloodGroup}
          onChange={(e) => setBloodGroup(e.target.value)}
          className="w-full p-3 rounded-xl mb-5 text-black"
        >
          <option value="">Select Blood Group</option>
          <option>O-</option>
          <option>O+</option>
          <option>A-</option>
          <option>A+</option>
          <option>B-</option>
          <option>B+</option>
          <option>AB-</option>
          <option>AB+</option>
        </select>

        <motion.button
          whileTap={{ scale: 0.95 }}
          whileHover={{ scale: 1.03 }}
          onClick={checkCompatibility}
          className="w-full bg-gradient-to-r from-red-600 to-rose-600 text-white p-3 rounded-xl font-semibold"
        >
          {loading ? "Checking..." : "Check Compatibility"}
        </motion.button>

        {result && (

          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-8 text-white"
          >

            <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <HeartHandshake className="text-pink-300"/>
              Blood Group: {result.data.blood_group}
            </h3>

            <div className="mb-5">
              <p className="font-semibold text-green-300">Can Donate To:</p>
              <div className="flex flex-wrap gap-2 mt-2">
                {result.data.can_donate_to.map((g,i)=>(
                  <span key={i} className="bg-green-500 px-3 py-1 rounded-full text-sm">
                    {g}
                  </span>
                ))}
              </div>
            </div>

            <div className="mb-6">
              <p className="font-semibold text-blue-300">Can Receive From:</p>
              <div className="flex flex-wrap gap-2 mt-2">
                {result.data.can_receive_from.map((g,i)=>(
                  <span key={i} className="bg-blue-500 px-3 py-1 rounded-full text-sm">
                    {g}
                  </span>
                ))}
              </div>
            </div>

            <button
              onClick={downloadPDF}
              className="flex items-center gap-2 bg-white text-black px-4 py-2 rounded-lg hover:bg-gray-200 transition"
            >
              <Download size={18}/>
              Download PDF
            </button>

          </motion.div>

        )}

      </motion.div>

    </div>

  )
}